alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
databases:
- engine: PG
  name: app-ayon-db
domains:
- domain: pipeline.chibifire.com
  type: PRIMARY
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: app-ayon-backend
    match:
      path:
        prefix: /
name: plankton-app
region: tor
services:
- dockerfile_path: Dockerfile
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${app-ayon-db.DATABASE_URL}
  github:
    branch: main
    deploy_on_push: true
    repo: V-Sekai-fire/app-ayon-backend
  http_port: 8080
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb
  name: app-ayon-backend
  source_dir: /
